### ISSUE TITLE
problems with compiling Vignette on CRAN

### ISSUE THREAD

**Issue by jeroenpullens** [jeroenpullens/NUCOMBog#7]

**Comment by jeroenpullens** [comment]
* checking files in 'vignettes' ... NOTE
The following directory looks like a leftover from 'knitr':
  'figure'
Please remove from your package.

**Comment by florianhartig** [comment]
That is clear enough, right? From where did you get this message, winbuilder?

**Comment by jeroenpullens** [comment]
It is indeed clear, but since the plots are not made by the vignette (as it needs an external executable) I cannot delete the folder. When I delete the folder, the figures are also lost.

**Comment by jeroenpullens** [comment]
and yes, it was indeed winbuilder. But I have been in contact with people from CRAN, so I will wait for their answer.

**Comment by florianhartig** [comment]
And if you just save the data for the plots with the package?

**Comment by jeroenpullens** [comment]
Added it, and it will be update on CRAN soon. Just got an email from CRAN
