### ISSUE TITLE
Connection with Travis CI cancelled

### ISSUE THREAD

**Issue by jeroenpullens** [jeroenpullens/NUCOMBog#8]
The R package suggests as dependent package: "RMPI". But with the installation on TRAVIS, this goes wrong.

**Comment by florianhartig** [comment]
Why do we even need to suggest Rmpi? The parallelization needs a cluster, doesn't need to be Rmpi, right?

**Comment by florianhartig** [comment]
I just had a look, the system needs mpi installed for Rmpi to compile ... I would erase the dependency - in various settings, suggest will try to install this on the computer of a user. If you simply want to suggest that the package can link to Rmpi, rather mention it in the vignette, or help (showing code with eval = F)

**Comment by jeroenpullens** [comment]
I needed the Rmpi for a cluster that i was trying to use.  But before I had the code ready the server was permanently down. This artifact stayed in the code. I have now taken it out, and reconnected with Travis. Now it build correclty
